# Generated by Django 3.0.6 on 2020-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='read_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
