# Generated by Django 3.0.6 on 2020-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_loveletter_read_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='like_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
