# Generated by Django 3.0.6 on 2020-10-10 04:55

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('blog_type', models.CharField(max_length=20)),
                ('content', mdeditor.fields.MDTextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('read_num', models.PositiveIntegerField(default=0)),
                ('like_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
